name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        apt update -qq > /dev/null && DEBIAN_FRONTEND=noninteractive apt install -qq --yes --no-install-recommends autoconf automake build-essential ccache cmake gettext git libffi-dev libltdl-dev libssl-dev libtool openjdk-17-jdk patch pkg-config python3-pip python3-setuptools sudo unzip zip zlib1g-dev
        pip install --upgrade pip
        pip install "Cython<3.0" wheel buildozer

    - name: Build APK
      run: |
        buildozer android debug
